CREATE DATABASE IF NOT EXISTS `SURVEY`;
USE SURVEY;

CREATE TABLE Question (
	Question_ID INT UNSIGNED  NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Question_Type varchar(255) NOT NULL,
    Question_Text TEXT NOT NULL,
    Question_Index INT UNSIGNED NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE Answer (
	Answer_ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Question_ID INT UNSIGNED NOT NULL,
    Answer_Text TEXT NOT NULL,
    Answer_Index INT UNSIGNED NOT NULL,
    CONSTRAINT FOREIGN KEY (Question_ID) REFERENCES Question(Question_ID)
) ENGINE=InnoDB;

CREATE TABLE Survey (
	Survey_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Survey_Duration TIME NOT NULL DEFAULT '00:02:00',
    Survey_Date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Survey_Index INT UNSIGNED NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE Reply (
	Reply_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Question_ID INT UNSIGNED NOT NULL,
    Answer_ID INT UNSIGNED NOT NULL,
    Survey_ID INT UNSIGNED NOT NULL,
    CONSTRAINT FOREIGN KEY (Survey_ID) REFERENCES Survey(Survey_ID),
    CONSTRAINT FOREIGN KEY (Answer_ID) REFERENCES Answer(Answer_ID),
    CONSTRAINT FOREIGN KEY (Question_ID) REFERENCES Question(Question_ID)
) ENGINE=InnoDB;

CREATE TABLE Admins (
	Admin_ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Admin_Username VARCHAR(100) NOT NULL UNIQUE,
    Admin_Email VARCHAR(100) UNIQUE NOT NULL,
    Admin_Password LONGTEXT NOT NULL,
    Admin_Name TEXT
) ENGINE=InnoDB;